config/routes.rb
Rails.application.routes.draw do
  
  resources :players, only: [:index, :create]
  get '/boards/:id', to: 'boards#show', as: 'board'
  get '/read_character', to: 'boards#read_character'
  root 'boards#index'
  
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :characters
  has_many :players
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :board
end

app/models/player.rb
class Player < ActiveRecord::Base
  before_validation :normalize_name, on: :create
  
  belongs_to :board
  validates :name, presence: true
  
  protected
    def normalize_name
      self.name = "Guest" if self.name.empty?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    find_board
    @characters = @board.characters
    @start = Time.now.to_i
  end
  
  def read_character
    find_board
    @characters = @board.characters
    render json: @characters
  end
  
  private
    def find_board
      @board = Board.find(params[:id])
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    search_players(params[:board_id])
    @start = Time.now.to_i - params[:start].to_i
  end

  def create
    @player = Player.new(player_params)
    if @player.save 
      search_players(@player.board_id)
      render :index
    else
      redirect_to root_path
    end
  end
  
  private
    def player_params
      params.require(:player).permit(:name, :score, :board_id)
    end
    
    def search_players(board)
      @board = Board.find(board)
      @players = @board.players.order('score asc').limit(20)
      @scores = @players.map { |p| p.score }
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/boards/index.html.erb
<div id="main">
  <h1>Find waldo</h1>
  <h3>Choose one...</h3>
  <% @boards.each do |board| %>
    <div class="level">
      <div class="name"><%= board.name %></div>
      <%= link_to image_tag(board.name, height: '250', width: '250'), board, class: "image" %>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<h1>Level: <%= @board.name.capitalize %></h1>
<div class="wrapper">
  <div class="bigimage">
    <%= image_tag(@board.name) %>
  </div>
  <div class="characterimage">
    <h3>Find...</h3>
    <% @characters.each do |character| %>
      <div class="char <%= character.name.downcase %>">
        <p><%= character.name %></p>
        <div class="thumbnail"><%= image_tag(character.name.downcase) %></div>
        <div class="checkmark"><%= image_tag("checkmark.png") %></div>
      </div>
    <% end %>
  </div>
  <div id="gameover">
    <p>You won!</p>
    <%= link_to "Click to continue...", players_path(board_id: @board.id, start: @start) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find Waldo game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/players/index.html.erb
<h1>Fastest times</h1>
<div class="scores">
  <% @players.each do |player| %>
    <div class="playername"><%= player.name %></div>
    <div class="score"><%= Time.at(player.score).utc.strftime("%H:%M:%S") %></div>
  <% end %>
</div>

<% if @player %>

  <div class="again"><%= link_to "Play again", root_path %></div>

<% else %>

  <div id="newentry">
    My score: <%= Time.at(@start).utc.strftime("%H:%M:%S") %>
    <% if @scores.length < 20 || @start <= @scores.max %>
      <% @player = Player.new %>
      <%= form_for @player, url: {controller: "players", action: "create"} do |f| %>
        <%= f.hidden_field 'score', :value => @start %>
        <%= f.hidden_field 'board_id', :value => @board.id %>    
        <%= f.text_field :name %>
        <%= f.submit %>
      <% end %>      
    <% else %>
      <div class="again"><%= link_to "Play again", root_path %></div>  
    <% end %>
  </div>

<% end %>